### ISSUE TITLE
comments after CE

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/c3-wolfram-crossword-solver#6]
+ step 4 seems to have an image that doesn't show
+ step 5 references a "previous task", which I assume is a different Wolfram project? Are these supposed to be done in a specific order? I think it's necessary to at least link to the project in question... either way it might be off-putting to learners that suddenly there's pre-supposed knowledge

**Comment by PhilipHarney** [comment]
@JaninaPi I'm not seeing the issue on [step 4](https://learning-admin.raspberrypi.org/en/projects/c3-wolfram-crossword-solver/4) here, all the images appear to render. Do you have the filename of the broken image?

For step five, it's just talking about the task on the previous page. I will admit it's a bit clunky there. Want me to take a quick swing at re-writing this step somewhat?

**Comment by JaninaPi** [comment]
step 4, line 14: ![wolfram alpha output](images/wolfram alpha.png)

Step 5: Ah, I didn't get that, I've made a small change so it doesn't mention 'previous task'. It would be good if you could have a look to double-check whether it's necessary to be more explicit with the instructions in the step. Let me know if you need me to look at any changes :)

**Comment by PhilipHarney** [comment]
<img width="776" alt="Screenshot 2019-04-01 at 13 42 51" src="https://user-images.githubusercontent.com/1235811/55328392-297d3b00-5484-11e9-8d13-1b2f83880e7d.png">

The image seems to show up for me on step 4, unless I'm really missing something…

Step 5 change looks good.

**Comment by JaninaPi** [comment]
Huh, weird. Consider it as working and move on, I guess?

**Comment by martinohanlon** [comment]
@PhilipHarney @JaninaPi  can this be closed?

**Comment by JaninaPi** [comment]
Yes from my side
